# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
