# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='ho'),
            preserve_default=False,
        ),
    ]
